FROM cc-tiledb-base:2.26

ARG TILEDB_LIB=/usr/local/lib/tiledb

ENV PATH=/go/bin:$PATH
ENV CGO_LDFLAGS="-L${TILEDB_LIB}/lib"
ENV CGO_CFLAGS="-I${TILEDB_LIB}/include"
ENV GOROOT=/go
ENV GOPATH=/src/go

RUN wget https://golang.org/dl/go1.23.9.linux-arm64.tar.gz -P / &&\
    tar -xvzf /go1.23.9.linux-arm64.tar.gz -C /
    